# Generated by Django 4.1.2 on 2022-10-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('document', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sale_opportunity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_vehicle', models.CharField(choices=[('h', 'Hatch'), ('s', 'Sedan'), ('c', 'Convertible')], default='h', max_length=1)),
                ('color', models.CharField(choices=[('y', 'Yellow'), ('b', 'Blue'), ('g', 'Gray')], default='g', max_length=1)),
                ('plate', models.CharField(blank=True, max_length=6, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
