# Generated by Django 4.1.2 on 2022-10-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
