# Generated by Django 4.1.2 on 2022-10-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('gray', 'Gray')], default='gray', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_vehicle',
            field=models.CharField(choices=[('hatch', 'Hatch'), ('sedan', 'Sedan'), ('convertible', 'Convertible')], default='hatch', max_length=20),
        ),
    ]
